export const CALCULATE = 'CALCULATE';
export const DELETEPRODUCT = 'DELETEPRODUCT';
export const CART_SETCOUNT = 'CART_SETCOUNT';
export const CART_RECEIVEPRODUCTS = 'CART_RECEIVEPRODUCTS';
export const ALLPRODUCTS = 'ALLPRODUCTS';
export const ADDTOCART = 'ADDTOCART';