export const CART_CALCULATE = 'CART_CALCULATE';
export const CART_DELETEPRODUCT = 'CART_DELETEPRODUCT';
export const CART_SETCOUNT = 'CART_SETCOUNT';
export const CART_RECEIVEPRODUCTS = 'CART_RECEIVEPRODUCTS';
export const CART_GETALL = 'CART_GETALL';

export const GOODS_ADDTOCART = 'GOODS_ADDTOCART';
export const GOODS_GETALL = 'GOODS_GETALL';