export const GOODS_GETALL = 'GOODS_GETALL';
export const GOODS_ADDTOCART = 'GOODS_ADDTOCART';
export const GOODS_SETCOUNTNUMBER = 'GOODS_SETCOUNTNUMBER';

export const CART_DELETEPRODUCT = 'CART_DELETEPRODUCT';
export const CART_RECEIVEPRODUCTS = 'CART_RECEIVEPRODUCTS';
export const CART_GETALL = 'CART_GETALL';